//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded.
public class NFD_NFD_Befunddaten {
    
    public static let namespacePrefix: String? = "NFD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/nfds/NFD_Document/v1.3"
    
    // attributes:
    
    // elements:
    public var Besondere_Hinweise: NFD_Besondere_Hinweise?
    public var Allergien_Unvertraeglichkeiten: [NFD_Allergien_Unvertraeglichkeiten]
    public var Diagnosen: [NFD_Diagnosen]
    
    // default Constructor
    public init() {
        
        self.Besondere_Hinweise = nil
        self.Allergien_Unvertraeglichkeiten = [NFD_Allergien_Unvertraeglichkeiten]()
        self.Diagnosen = [NFD_Diagnosen]()
        
    }
    
    // copy Constructor
    public init(_ _NFD_NFD_Befunddaten: NFD_NFD_Befunddaten ) {
        
        self.Besondere_Hinweise = _NFD_NFD_Befunddaten.Besondere_Hinweise
        self.Allergien_Unvertraeglichkeiten = _NFD_NFD_Befunddaten.Allergien_Unvertraeglichkeiten
        self.Diagnosen = _NFD_NFD_Befunddaten.Diagnosen
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> NFD_NFD_Befunddaten {
        
        let _NFD_NFD_Befunddaten = NFD_NFD_Befunddaten()
        
        let uriBesondere_Hinweise = NFD_Besondere_Hinweise.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameBesondere_Hinweise = QName("Besondere_Hinweise", uri: uriBesondere_Hinweise)
        _NFD_NFD_Befunddaten.Besondere_Hinweise = NFD_Besondere_Hinweise?.deserialize(infoset.select(qNameBesondere_Hinweise))
        
        let uriAllergien_Unvertraeglichkeiten = [NFD_Allergien_Unvertraeglichkeiten]().namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameAllergien_Unvertraeglichkeiten = QName("Allergien_Unvertraeglichkeiten", uri: uriAllergien_Unvertraeglichkeiten)
        _NFD_NFD_Befunddaten.Allergien_Unvertraeglichkeiten = [NFD_Allergien_Unvertraeglichkeiten].deserialize(infoset.select(qNameAllergien_Unvertraeglichkeiten))
        
        let uriDiagnosen = [NFD_Diagnosen]().namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDiagnosen = QName("Diagnosen", uri: uriDiagnosen)
        _NFD_NFD_Befunddaten.Diagnosen = [NFD_Diagnosen].deserialize(infoset.select(qNameDiagnosen))
        
        return _NFD_NFD_Befunddaten
    }
}

extension Optional where Wrapped == NFD_NFD_Befunddaten {
    public static func deserialize(_ infoset: Infoset) -> NFD_NFD_Befunddaten? {
        if infoset.count == 0 {
            return nil
        } else {
            return NFD_NFD_Befunddaten.deserialize(infoset)
        }
    }
}

extension Array where Element: NFD_NFD_Befunddaten {
    public var namespaceUri: String? {
        get {
            return NFD_NFD_Befunddaten.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [NFD_NFD_Befunddaten] {
        return infoset.map { (element: Infoset) in
        NFD_NFD_Befunddaten.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

