//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded.
public class NFD_NFD_Document {
    
    public static let namespacePrefix: String? = "NFD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/nfds/NFD_Document/v1.3"
    
    // attributes:
    public var NFD_Version: String
    
    // elements:
    public var Notfalldaten: NFD_Notfalldaten
    public var SignatureArzt: NFD_SignatureArzt
    
    // default Constructor
    public init() {
        
        self.NFD_Version = String()
        
        self.Notfalldaten = NFD_Notfalldaten()
        self.SignatureArzt = NFD_SignatureArzt()
        
    }
    
    // copy Constructor
    public init(_ _NFD_NFD_Document: NFD_NFD_Document ) {
        
        self.NFD_Version = _NFD_NFD_Document.NFD_Version
        
        self.Notfalldaten = _NFD_NFD_Document.Notfalldaten
        self.SignatureArzt = _NFD_NFD_Document.SignatureArzt
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> NFD_NFD_Document {
        
        let _NFD_NFD_Document = NFD_NFD_Document()
        
        _NFD_NFD_Document.NFD_Version = String.deserialize(infoset.attr("NFD_Version"))
        
        let uriNotfalldaten = NFD_Notfalldaten.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameNotfalldaten = QName("Notfalldaten", uri: uriNotfalldaten)
        _NFD_NFD_Document.Notfalldaten = NFD_Notfalldaten.deserialize(infoset.select(qNameNotfalldaten))
        
        let uriSignatureArzt = NFD_SignatureArzt.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameSignatureArzt = QName("SignatureArzt", uri: uriSignatureArzt)
        _NFD_NFD_Document.SignatureArzt = NFD_SignatureArzt.deserialize(infoset.select(qNameSignatureArzt))
        
        return _NFD_NFD_Document
    }
}

extension Optional where Wrapped == NFD_NFD_Document {
    public static func deserialize(_ infoset: Infoset) -> NFD_NFD_Document? {
        if infoset.count == 0 {
            return nil
        } else {
            return NFD_NFD_Document.deserialize(infoset)
        }
    }
}

extension Array where Element: NFD_NFD_Document {
    public var namespaceUri: String? {
        get {
            return NFD_NFD_Document.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [NFD_NFD_Document] {
        return infoset.map { (element: Infoset) in
        NFD_NFD_Document.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

