//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded.
public class NFD_DI_Institution {
    
    public static let namespacePrefix: String? = "NFD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/nfds/NFD_Document/v1.3"
    
    // attributes:
    
    // elements:
    public var DI_Institution_Name: String
    public var DI_Institution_Fachabteilung: String
    public var DI_Institution_Ort: String
    
    // default Constructor
    public init() {
        
        self.DI_Institution_Name = String()
        self.DI_Institution_Fachabteilung = String()
        self.DI_Institution_Ort = String()
        
    }
    
    // copy Constructor
    public init(_ _NFD_DI_Institution: NFD_DI_Institution ) {
        
        self.DI_Institution_Name = _NFD_DI_Institution.DI_Institution_Name
        self.DI_Institution_Fachabteilung = _NFD_DI_Institution.DI_Institution_Fachabteilung
        self.DI_Institution_Ort = _NFD_DI_Institution.DI_Institution_Ort
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> NFD_DI_Institution {
        
        let _NFD_DI_Institution = NFD_DI_Institution()
        
        let uriDI_Institution_Name = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDI_Institution_Name = QName("DI_Institution_Name", uri: uriDI_Institution_Name)
        _NFD_DI_Institution.DI_Institution_Name = String.deserialize(infoset.select(qNameDI_Institution_Name))
        
        let uriDI_Institution_Fachabteilung = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDI_Institution_Fachabteilung = QName("DI_Institution_Fachabteilung", uri: uriDI_Institution_Fachabteilung)
        _NFD_DI_Institution.DI_Institution_Fachabteilung = String.deserialize(infoset.select(qNameDI_Institution_Fachabteilung))
        
        let uriDI_Institution_Ort = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDI_Institution_Ort = QName("DI_Institution_Ort", uri: uriDI_Institution_Ort)
        _NFD_DI_Institution.DI_Institution_Ort = String.deserialize(infoset.select(qNameDI_Institution_Ort))
        
        return _NFD_DI_Institution
    }
}

extension Optional where Wrapped == NFD_DI_Institution {
    public static func deserialize(_ infoset: Infoset) -> NFD_DI_Institution? {
        if infoset.count == 0 {
            return nil
        } else {
            return NFD_DI_Institution.deserialize(infoset)
        }
    }
}

extension Array where Element: NFD_DI_Institution {
    public var namespaceUri: String? {
        get {
            return NFD_DI_Institution.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [NFD_DI_Institution] {
        return infoset.map { (element: Infoset) in
        NFD_DI_Institution.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

