//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded.
public class NFD_NFD_Medikationseintrag {
    
    public static let namespacePrefix: String? = "NFD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/nfds/NFD_Document/v1.3"
    
    // attributes:
    
    // elements:
    public var diagnostiziert_indiziert: NFD_Diagnose_Indikation?
    public var M: NFD_M?
    public var R: NFD_R?
    
    // default Constructor
    public init() {
        
        self.diagnostiziert_indiziert = nil
        self.M = nil
        self.R = nil
        
    }
    
    // copy Constructor
    public init(_ _NFD_NFD_Medikationseintrag: NFD_NFD_Medikationseintrag ) {
        
        self.diagnostiziert_indiziert = _NFD_NFD_Medikationseintrag.diagnostiziert_indiziert
        self.M = _NFD_NFD_Medikationseintrag.M
        self.R = _NFD_NFD_Medikationseintrag.R
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> NFD_NFD_Medikationseintrag {
        
        let _NFD_NFD_Medikationseintrag = NFD_NFD_Medikationseintrag()
        
        let uridiagnostiziert_indiziert = NFD_Diagnose_Indikation.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNamediagnostiziert_indiziert = QName("diagnostiziert_indiziert", uri: uridiagnostiziert_indiziert)
        _NFD_NFD_Medikationseintrag.diagnostiziert_indiziert = NFD_Diagnose_Indikation?.deserialize(infoset.select(qNamediagnostiziert_indiziert))
        
        let uriM = NFD_M.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameM = QName("M", uri: uriM)
        _NFD_NFD_Medikationseintrag.M = NFD_M?.deserialize(infoset.select(qNameM))
        
        let uriR = NFD_R.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameR = QName("R", uri: uriR)
        _NFD_NFD_Medikationseintrag.R = NFD_R?.deserialize(infoset.select(qNameR))
        
        return _NFD_NFD_Medikationseintrag
    }
}

extension Optional where Wrapped == NFD_NFD_Medikationseintrag {
    public static func deserialize(_ infoset: Infoset) -> NFD_NFD_Medikationseintrag? {
        if infoset.count == 0 {
            return nil
        } else {
            return NFD_NFD_Medikationseintrag.deserialize(infoset)
        }
    }
}

extension Array where Element: NFD_NFD_Medikationseintrag {
    public var namespaceUri: String? {
        get {
            return NFD_NFD_Medikationseintrag.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [NFD_NFD_Medikationseintrag] {
        return infoset.map { (element: Infoset) in
        NFD_NFD_Medikationseintrag.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

