//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded.
public class NFD_Diagnose_Indikation {
    
    public static let namespacePrefix: String? = "NFD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/nfds/NFD_Document/v1.3"
    
    // attributes:
    public var DI_Art: String
    
    // elements:
    public var DI_Arzt: NFD_DI_Arzt?
    public var DI_Institution: NFD_DI_Institution?
    
    // default Constructor
    public init() {
        
        self.DI_Art = String()
        
        self.DI_Arzt = nil
        self.DI_Institution = nil
        
    }
    
    // copy Constructor
    public init(_ _NFD_Diagnose_Indikation: NFD_Diagnose_Indikation ) {
        
        self.DI_Art = _NFD_Diagnose_Indikation.DI_Art
        
        self.DI_Arzt = _NFD_Diagnose_Indikation.DI_Arzt
        self.DI_Institution = _NFD_Diagnose_Indikation.DI_Institution
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> NFD_Diagnose_Indikation {
        
        let _NFD_Diagnose_Indikation = NFD_Diagnose_Indikation()
        
        _NFD_Diagnose_Indikation.DI_Art = String.deserialize(infoset.attr("DI_Art"))
        
        let uriDI_Arzt = NFD_DI_Arzt.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDI_Arzt = QName("DI_Arzt", uri: uriDI_Arzt)
        _NFD_Diagnose_Indikation.DI_Arzt = NFD_DI_Arzt?.deserialize(infoset.select(qNameDI_Arzt))
        
        let uriDI_Institution = NFD_DI_Institution.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDI_Institution = QName("DI_Institution", uri: uriDI_Institution)
        _NFD_Diagnose_Indikation.DI_Institution = NFD_DI_Institution?.deserialize(infoset.select(qNameDI_Institution))
        
        return _NFD_Diagnose_Indikation
    }
}

extension Optional where Wrapped == NFD_Diagnose_Indikation {
    public static func deserialize(_ infoset: Infoset) -> NFD_Diagnose_Indikation? {
        if infoset.count == 0 {
            return nil
        } else {
            return NFD_Diagnose_Indikation.deserialize(infoset)
        }
    }
}

extension Array where Element: NFD_Diagnose_Indikation {
    public var namespaceUri: String? {
        get {
            return NFD_Diagnose_Indikation.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [NFD_Diagnose_Indikation] {
        return infoset.map { (element: Infoset) in
        NFD_Diagnose_Indikation.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

