//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded.
public class NFD_Besondere_Hinweise {
    
    public static let namespacePrefix: String? = "NFD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/nfds/NFD_Document/v1.4"
    
    // attributes:
    
    // elements:
    public var Schwangerschaft: NFD_Schwangerschaft?
    public var Implantate: [NFD_Implantate]
    public var Kommunikationsstoerungen: [NFD_Kommunikationsstoerungen]
    public var Weglaufgefaehrdung: NFD_Weglaufgefaehrdung?
    public var Sonstige_Hinweise: [NFD_Sonstige_Hinweise]
    
    // default Constructor
    public init() {
        
        self.Schwangerschaft = nil
        self.Implantate = [NFD_Implantate]()
        self.Kommunikationsstoerungen = [NFD_Kommunikationsstoerungen]()
        self.Weglaufgefaehrdung = nil
        self.Sonstige_Hinweise = [NFD_Sonstige_Hinweise]()
        
    }
    
    // copy Constructor
    public init(_ _NFD_Besondere_Hinweise: NFD_Besondere_Hinweise ) {
        
        self.Schwangerschaft = _NFD_Besondere_Hinweise.Schwangerschaft
        self.Implantate = _NFD_Besondere_Hinweise.Implantate
        self.Kommunikationsstoerungen = _NFD_Besondere_Hinweise.Kommunikationsstoerungen
        self.Weglaufgefaehrdung = _NFD_Besondere_Hinweise.Weglaufgefaehrdung
        self.Sonstige_Hinweise = _NFD_Besondere_Hinweise.Sonstige_Hinweise
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> NFD_Besondere_Hinweise {
        
        let _NFD_Besondere_Hinweise = NFD_Besondere_Hinweise()
        
        let uriSchwangerschaft = NFD_Schwangerschaft.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameSchwangerschaft = QName("Schwangerschaft", uri: uriSchwangerschaft)
        _NFD_Besondere_Hinweise.Schwangerschaft = NFD_Schwangerschaft?.deserialize(infoset.select(qNameSchwangerschaft))
        
        let uriImplantate = [NFD_Implantate]().namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameImplantate = QName("Implantate", uri: uriImplantate)
        _NFD_Besondere_Hinweise.Implantate = [NFD_Implantate].deserialize(infoset.select(qNameImplantate))
        
        let uriKommunikationsstoerungen = [NFD_Kommunikationsstoerungen]().namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameKommunikationsstoerungen = QName("Kommunikationsstoerungen", uri: uriKommunikationsstoerungen)
        _NFD_Besondere_Hinweise.Kommunikationsstoerungen = [NFD_Kommunikationsstoerungen].deserialize(infoset.select(qNameKommunikationsstoerungen))
        
        let uriWeglaufgefaehrdung = NFD_Weglaufgefaehrdung.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameWeglaufgefaehrdung = QName("Weglaufgefaehrdung", uri: uriWeglaufgefaehrdung)
        _NFD_Besondere_Hinweise.Weglaufgefaehrdung = NFD_Weglaufgefaehrdung?.deserialize(infoset.select(qNameWeglaufgefaehrdung))
        
        let uriSonstige_Hinweise = [NFD_Sonstige_Hinweise]().namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameSonstige_Hinweise = QName("Sonstige_Hinweise", uri: uriSonstige_Hinweise)
        _NFD_Besondere_Hinweise.Sonstige_Hinweise = [NFD_Sonstige_Hinweise].deserialize(infoset.select(qNameSonstige_Hinweise))
        
        return _NFD_Besondere_Hinweise
    }
}

extension Optional where Wrapped == NFD_Besondere_Hinweise {
    public static func deserialize(_ infoset: Infoset) -> NFD_Besondere_Hinweise? {
        if infoset.count == 0 {
            return nil
        } else {
            return NFD_Besondere_Hinweise.deserialize(infoset)
        }
    }
}

extension Array where Element: NFD_Besondere_Hinweise {
    public var namespaceUri: String? {
        get {
            return NFD_Besondere_Hinweise.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [NFD_Besondere_Hinweise] {
        return infoset.map { (element: Infoset) in
        NFD_Besondere_Hinweise.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

