//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded.
public class NFD_Weglaufgefaehrdung {
    
    public static let namespacePrefix: String? = "NFD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/nfds/NFD_Document/v1.4"
    
    // attributes:
    
    // elements:
    public var Weglaufgefaehrdung: String
    public var Weglaufgefaehrdung_Erlaeuterung: String
    public var diagnostiziert_indiziert: NFD_Diagnose_Indikation?
    
    // default Constructor
    public init() {
        
        self.Weglaufgefaehrdung = String()
        self.Weglaufgefaehrdung_Erlaeuterung = String()
        self.diagnostiziert_indiziert = nil
        
    }
    
    // copy Constructor
    public init(_ _NFD_Weglaufgefaehrdung: NFD_Weglaufgefaehrdung ) {
        
        self.Weglaufgefaehrdung = _NFD_Weglaufgefaehrdung.Weglaufgefaehrdung
        self.Weglaufgefaehrdung_Erlaeuterung = _NFD_Weglaufgefaehrdung.Weglaufgefaehrdung_Erlaeuterung
        self.diagnostiziert_indiziert = _NFD_Weglaufgefaehrdung.diagnostiziert_indiziert
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> NFD_Weglaufgefaehrdung {
        
        let _NFD_Weglaufgefaehrdung = NFD_Weglaufgefaehrdung()
        
        let uriWeglaufgefaehrdung = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameWeglaufgefaehrdung = QName("Weglaufgefaehrdung", uri: uriWeglaufgefaehrdung)
        _NFD_Weglaufgefaehrdung.Weglaufgefaehrdung = String.deserialize(infoset.select(qNameWeglaufgefaehrdung))
        
        let uriWeglaufgefaehrdung_Erlaeuterung = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameWeglaufgefaehrdung_Erlaeuterung = QName("Weglaufgefaehrdung_Erlaeuterung", uri: uriWeglaufgefaehrdung_Erlaeuterung)
        _NFD_Weglaufgefaehrdung.Weglaufgefaehrdung_Erlaeuterung = String.deserialize(infoset.select(qNameWeglaufgefaehrdung_Erlaeuterung))
        
        let uridiagnostiziert_indiziert = NFD_Diagnose_Indikation.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNamediagnostiziert_indiziert = QName("diagnostiziert_indiziert", uri: uridiagnostiziert_indiziert)
        _NFD_Weglaufgefaehrdung.diagnostiziert_indiziert = NFD_Diagnose_Indikation?.deserialize(infoset.select(qNamediagnostiziert_indiziert))
        
        return _NFD_Weglaufgefaehrdung
    }
}

extension Optional where Wrapped == NFD_Weglaufgefaehrdung {
    public static func deserialize(_ infoset: Infoset) -> NFD_Weglaufgefaehrdung? {
        if infoset.count == 0 {
            return nil
        } else {
            return NFD_Weglaufgefaehrdung.deserialize(infoset)
        }
    }
}

extension Array where Element: NFD_Weglaufgefaehrdung {
    public var namespaceUri: String? {
        get {
            return NFD_Weglaufgefaehrdung.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [NFD_Weglaufgefaehrdung] {
        return infoset.map { (element: Infoset) in
        NFD_Weglaufgefaehrdung.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

