//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded.
public class NFD_Notfalldaten {
    
    public static let namespacePrefix: String? = "NFD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/nfds/NFD_Document/v1.4"
    
    // attributes:
    public var ID_NFD: String
    public var ID: String
    public var NFD_letzte_Aktualisierung_date: String
    public var NFD_letzte_Aktualisierung_time: String
    
    // elements:
    public var NFD_Versicherter: NFD_NFD_Versicherter
    public var NFD_Versicherter_Einwilligung: NFD_NFD_Versicherter_Einwilligung
    public var NFD_Befunddaten: NFD_NFD_Befunddaten?
    public var NFD_Medikationseintrag: [NFD_NFD_Medikationseintrag]
    public var NFD_Freiwillige_Zusatzinformationen: NFD_NFD_Freiwillige_Zusatzinformationen?
    
    // default Constructor
    public init() {
        
        self.ID_NFD = String()
        self.ID = String()
        self.NFD_letzte_Aktualisierung_date = String()
        self.NFD_letzte_Aktualisierung_time = String()
        
        self.NFD_Versicherter = NFD_NFD_Versicherter()
        self.NFD_Versicherter_Einwilligung = NFD_NFD_Versicherter_Einwilligung()
        self.NFD_Befunddaten = nil
        self.NFD_Medikationseintrag = [NFD_NFD_Medikationseintrag]()
        self.NFD_Freiwillige_Zusatzinformationen = nil
        
    }
    
    // copy Constructor
    public init(_ _NFD_Notfalldaten: NFD_Notfalldaten ) {
        
        self.ID_NFD = _NFD_Notfalldaten.ID_NFD
        self.ID = _NFD_Notfalldaten.ID
        self.NFD_letzte_Aktualisierung_date = _NFD_Notfalldaten.NFD_letzte_Aktualisierung_date
        self.NFD_letzte_Aktualisierung_time = _NFD_Notfalldaten.NFD_letzte_Aktualisierung_time
        
        self.NFD_Versicherter = _NFD_Notfalldaten.NFD_Versicherter
        self.NFD_Versicherter_Einwilligung = _NFD_Notfalldaten.NFD_Versicherter_Einwilligung
        self.NFD_Befunddaten = _NFD_Notfalldaten.NFD_Befunddaten
        self.NFD_Medikationseintrag = _NFD_Notfalldaten.NFD_Medikationseintrag
        self.NFD_Freiwillige_Zusatzinformationen = _NFD_Notfalldaten.NFD_Freiwillige_Zusatzinformationen
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> NFD_Notfalldaten {
        
        let _NFD_Notfalldaten = NFD_Notfalldaten()
        
        _NFD_Notfalldaten.ID_NFD = String.deserialize(infoset.attr("ID_NFD"))
        _NFD_Notfalldaten.ID = String.deserialize(infoset.attr("ID"))
        _NFD_Notfalldaten.NFD_letzte_Aktualisierung_date = String.deserialize(infoset.attr("NFD_letzte_Aktualisierung_date"))
        _NFD_Notfalldaten.NFD_letzte_Aktualisierung_time = String.deserialize(infoset.attr("NFD_letzte_Aktualisierung_time"))
        
        let uriNFD_Versicherter = NFD_NFD_Versicherter.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameNFD_Versicherter = QName("NFD_Versicherter", uri: uriNFD_Versicherter)
        _NFD_Notfalldaten.NFD_Versicherter = NFD_NFD_Versicherter.deserialize(infoset.select(qNameNFD_Versicherter))
        
        let uriNFD_Versicherter_Einwilligung = NFD_NFD_Versicherter_Einwilligung.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameNFD_Versicherter_Einwilligung = QName("NFD_Versicherter_Einwilligung", uri: uriNFD_Versicherter_Einwilligung)
        _NFD_Notfalldaten.NFD_Versicherter_Einwilligung = NFD_NFD_Versicherter_Einwilligung.deserialize(infoset.select(qNameNFD_Versicherter_Einwilligung))
        
        let uriNFD_Befunddaten = NFD_NFD_Befunddaten.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameNFD_Befunddaten = QName("NFD_Befunddaten", uri: uriNFD_Befunddaten)
        _NFD_Notfalldaten.NFD_Befunddaten = NFD_NFD_Befunddaten?.deserialize(infoset.select(qNameNFD_Befunddaten))
        
        let uriNFD_Medikationseintrag = [NFD_NFD_Medikationseintrag]().namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameNFD_Medikationseintrag = QName("NFD_Medikationseintrag", uri: uriNFD_Medikationseintrag)
        _NFD_Notfalldaten.NFD_Medikationseintrag = [NFD_NFD_Medikationseintrag].deserialize(infoset.select(qNameNFD_Medikationseintrag))
        
        let uriNFD_Freiwillige_Zusatzinformationen = NFD_NFD_Freiwillige_Zusatzinformationen.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameNFD_Freiwillige_Zusatzinformationen = QName("NFD_Freiwillige_Zusatzinformationen", uri: uriNFD_Freiwillige_Zusatzinformationen)
        _NFD_Notfalldaten.NFD_Freiwillige_Zusatzinformationen = NFD_NFD_Freiwillige_Zusatzinformationen?.deserialize(infoset.select(qNameNFD_Freiwillige_Zusatzinformationen))
        
        return _NFD_Notfalldaten
    }
}

extension Optional where Wrapped == NFD_Notfalldaten {
    public static func deserialize(_ infoset: Infoset) -> NFD_Notfalldaten? {
        if infoset.count == 0 {
            return nil
        } else {
            return NFD_Notfalldaten.deserialize(infoset)
        }
    }
}

extension Array where Element: NFD_Notfalldaten {
    public var namespaceUri: String? {
        get {
            return NFD_Notfalldaten.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [NFD_Notfalldaten] {
        return infoset.map { (element: Infoset) in
        NFD_Notfalldaten.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

