//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded.
public class NFD_NFD_Versicherter {
    
    public static let namespacePrefix: String? = "NFD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/nfds/NFD_Document/v1.4"
    
    // attributes:
    
    // elements:
    public var Versicherter: NFDM_Versicherter
    public var NFD_Behandelnder_Arzt_Institution: [NFD_NFD_Behandelnder_Arzt_Institution]
    public var NFD_Benachrichtigungskontakt: NFD_NFD_Benachrichtigungskontakt?
    public var NFD_Versicherter_Kommunikation: [NFD_NFD_Kommunikationsdaten]
    
    // default Constructor
    public init() {
        
        self.Versicherter = NFDM_Versicherter()
        self.NFD_Behandelnder_Arzt_Institution = [NFD_NFD_Behandelnder_Arzt_Institution]()
        self.NFD_Benachrichtigungskontakt = nil
        self.NFD_Versicherter_Kommunikation = [NFD_NFD_Kommunikationsdaten]()
        
    }
    
    // copy Constructor
    public init(_ _NFD_NFD_Versicherter: NFD_NFD_Versicherter ) {
        
        self.Versicherter = _NFD_NFD_Versicherter.Versicherter
        self.NFD_Behandelnder_Arzt_Institution = _NFD_NFD_Versicherter.NFD_Behandelnder_Arzt_Institution
        self.NFD_Benachrichtigungskontakt = _NFD_NFD_Versicherter.NFD_Benachrichtigungskontakt
        self.NFD_Versicherter_Kommunikation = _NFD_NFD_Versicherter.NFD_Versicherter_Kommunikation
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> NFD_NFD_Versicherter {
        
        let _NFD_NFD_Versicherter = NFD_NFD_Versicherter()
        
        let uriVersicherter = NFDM_Versicherter.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameVersicherter = QName("Versicherter", uri: uriVersicherter)
        _NFD_NFD_Versicherter.Versicherter = NFDM_Versicherter.deserialize(infoset.select(qNameVersicherter))
        
        let uriNFD_Behandelnder_Arzt_Institution = [NFD_NFD_Behandelnder_Arzt_Institution]().namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameNFD_Behandelnder_Arzt_Institution = QName("NFD_Behandelnder_Arzt_Institution", uri: uriNFD_Behandelnder_Arzt_Institution)
        _NFD_NFD_Versicherter.NFD_Behandelnder_Arzt_Institution = [NFD_NFD_Behandelnder_Arzt_Institution].deserialize(infoset.select(qNameNFD_Behandelnder_Arzt_Institution))
        
        let uriNFD_Benachrichtigungskontakt = NFD_NFD_Benachrichtigungskontakt.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameNFD_Benachrichtigungskontakt = QName("NFD_Benachrichtigungskontakt", uri: uriNFD_Benachrichtigungskontakt)
        _NFD_NFD_Versicherter.NFD_Benachrichtigungskontakt = NFD_NFD_Benachrichtigungskontakt?.deserialize(infoset.select(qNameNFD_Benachrichtigungskontakt))
        
        let uriNFD_Versicherter_Kommunikation = [NFD_NFD_Kommunikationsdaten]().namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameNFD_Versicherter_Kommunikation = QName("NFD_Versicherter_Kommunikation", uri: uriNFD_Versicherter_Kommunikation)
        _NFD_NFD_Versicherter.NFD_Versicherter_Kommunikation = [NFD_NFD_Kommunikationsdaten].deserialize(infoset.select(qNameNFD_Versicherter_Kommunikation))
        
        return _NFD_NFD_Versicherter
    }
}

extension Optional where Wrapped == NFD_NFD_Versicherter {
    public static func deserialize(_ infoset: Infoset) -> NFD_NFD_Versicherter? {
        if infoset.count == 0 {
            return nil
        } else {
            return NFD_NFD_Versicherter.deserialize(infoset)
        }
    }
}

extension Array where Element: NFD_NFD_Versicherter {
    public var namespaceUri: String? {
        get {
            return NFD_NFD_Versicherter.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [NFD_NFD_Versicherter] {
        return infoset.map { (element: Infoset) in
        NFD_NFD_Versicherter.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

