//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded.
public class NFDM_Adresse {
    
    public static let namespacePrefix: String? = "NFDM"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/nfds/common/NFDM_Common/v1.1"
    
    // attributes:
    
    // elements:
    public var Postleitzahl: String
    public var Ort: String
    public var Strasse: String
    public var Hausnummer: String
    public var Anschriftenzusatz: String?
    public var Wohnsitzlaendercode: String?
    
    // default Constructor
    public init() {
        
        self.Postleitzahl = String()
        self.Ort = String()
        self.Strasse = String()
        self.Hausnummer = String()
        self.Anschriftenzusatz = nil
        self.Wohnsitzlaendercode = nil
        
    }
    
    // copy Constructor
    public init(_ _NFDM_Adresse: NFDM_Adresse ) {
        
        self.Postleitzahl = _NFDM_Adresse.Postleitzahl
        self.Ort = _NFDM_Adresse.Ort
        self.Strasse = _NFDM_Adresse.Strasse
        self.Hausnummer = _NFDM_Adresse.Hausnummer
        self.Anschriftenzusatz = _NFDM_Adresse.Anschriftenzusatz
        self.Wohnsitzlaendercode = _NFDM_Adresse.Wohnsitzlaendercode
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> NFDM_Adresse {
        
        let _NFDM_Adresse = NFDM_Adresse()
        
        let uriPostleitzahl = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNamePostleitzahl = QName("Postleitzahl", uri: uriPostleitzahl)
        _NFDM_Adresse.Postleitzahl = String.deserialize(infoset.select(qNamePostleitzahl))
        
        let uriOrt = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameOrt = QName("Ort", uri: uriOrt)
        _NFDM_Adresse.Ort = String.deserialize(infoset.select(qNameOrt))
        
        let uriStrasse = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameStrasse = QName("Strasse", uri: uriStrasse)
        _NFDM_Adresse.Strasse = String.deserialize(infoset.select(qNameStrasse))
        
        let uriHausnummer = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameHausnummer = QName("Hausnummer", uri: uriHausnummer)
        _NFDM_Adresse.Hausnummer = String.deserialize(infoset.select(qNameHausnummer))
        
        let uriAnschriftenzusatz = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameAnschriftenzusatz = QName("Anschriftenzusatz", uri: uriAnschriftenzusatz)
        _NFDM_Adresse.Anschriftenzusatz = String?.deserialize(infoset.select(qNameAnschriftenzusatz))
        
        let uriWohnsitzlaendercode = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameWohnsitzlaendercode = QName("Wohnsitzlaendercode", uri: uriWohnsitzlaendercode)
        _NFDM_Adresse.Wohnsitzlaendercode = String?.deserialize(infoset.select(qNameWohnsitzlaendercode))
        
        return _NFDM_Adresse
    }
}

extension Optional where Wrapped == NFDM_Adresse {
    public static func deserialize(_ infoset: Infoset) -> NFDM_Adresse? {
        if infoset.count == 0 {
            return nil
        } else {
            return NFDM_Adresse.deserialize(infoset)
        }
    }
}

extension Array where Element: NFDM_Adresse {
    public var namespaceUri: String? {
        get {
            return NFDM_Adresse.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [NFDM_Adresse] {
        return infoset.map { (element: Infoset) in
        NFDM_Adresse.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

