//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded.
public class NFDM_Kommunikationsdaten {
    
    public static let namespacePrefix: String? = "NFDM"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/nfds/common/NFDM_Common/v1.1"
    
    // attributes:
    
    // elements:
    public var Telefonnummer: String
    public var Faxnummer: String?
    public var EMail: String?
    
    // default Constructor
    public init() {
        
        self.Telefonnummer = String()
        self.Faxnummer = nil
        self.EMail = nil
        
    }
    
    // copy Constructor
    public init(_ _NFDM_Kommunikationsdaten: NFDM_Kommunikationsdaten ) {
        
        self.Telefonnummer = _NFDM_Kommunikationsdaten.Telefonnummer
        self.Faxnummer = _NFDM_Kommunikationsdaten.Faxnummer
        self.EMail = _NFDM_Kommunikationsdaten.EMail
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> NFDM_Kommunikationsdaten {
        
        let _NFDM_Kommunikationsdaten = NFDM_Kommunikationsdaten()
        
        let uriTelefonnummer = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameTelefonnummer = QName("Telefonnummer", uri: uriTelefonnummer)
        _NFDM_Kommunikationsdaten.Telefonnummer = String.deserialize(infoset.select(qNameTelefonnummer))
        
        let uriFaxnummer = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameFaxnummer = QName("Faxnummer", uri: uriFaxnummer)
        _NFDM_Kommunikationsdaten.Faxnummer = String?.deserialize(infoset.select(qNameFaxnummer))
        
        let uriEMail = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameEMail = QName("E-Mail", uri: uriEMail)
        _NFDM_Kommunikationsdaten.EMail = String?.deserialize(infoset.select(qNameEMail))
        
        return _NFDM_Kommunikationsdaten
    }
}

extension Optional where Wrapped == NFDM_Kommunikationsdaten {
    public static func deserialize(_ infoset: Infoset) -> NFDM_Kommunikationsdaten? {
        if infoset.count == 0 {
            return nil
        } else {
            return NFDM_Kommunikationsdaten.deserialize(infoset)
        }
    }
}

extension Array where Element: NFDM_Kommunikationsdaten {
    public var namespaceUri: String? {
        get {
            return NFDM_Kommunikationsdaten.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [NFDM_Kommunikationsdaten] {
        return infoset.map { (element: Infoset) in
        NFDM_Kommunikationsdaten.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

